[#31] Improve the UX flow for the Log In mode switch button at the bo…
lbryio/odysee-ios pull request #224
Opened 2021-07-21 07:05 UTC by kroucis

[#31] Improve the UX flow for the Log In mode switch button at the bottom of the "Join Odysee" view by changing the tappable label to a full-fledged rounded button.

New Sign Up view:
![Simulator Screen Shot - iPhone 8 - 2021-07-21 at 03 04 09](https://user-images.githubusercontent.com/1031501/126445931-e3fbc409-7bc0-445b-8a5f-4bf19a39bbfe.png)

New Log In view:
![Simulator Screen Shot - iPhone 8 - 2021-07-21 at 03 04 21](https://user-images.githubusercontent.com/1031501/126445958-f054af54-0261-4269-bd5c-75a74868ac88.png)

2021-07-21 10:46 UTC, akinwale requested changes
This looks good, thanks. Could you make the button at the bottom half the length of the main button? Once you push up your commit, I'll merge the change.

2021-07-21 16:18 UTC, kroucis commented
I had to get....destructive to get IB to allow the 1/2 width button request. It *really* did not like a 0.5 multiplier on the button while it was in the StackView (and I couldn't just add the 1/2 width constraint to the StackView because the label was effected too). So I ended up removing the StackView altogether and now the Log In button is the anchor for the label at the bottom.

New Sign Up view with half-width button
![Simulator Screen Shot - iPhone 8 - 2021-07-21 at 12 17 46](https://user-images.githubusercontent.com/1031501/126523513-3b61314c-9530-4e2b-97a4-dc504e8464d5.png)

New Log In view with half-width button
![Simulator Screen Shot - iPhone 8 - 2021-07-21 at 12 18 25](https://user-images.githubusercontent.com/1031501/126523591-081ec3c8-5c35-4c51-a8bc-9350aace0997.png)

2021-07-23 19:53 UTC, kroucis commented
Bumping this thread. The button size change has been implemented and is ready for another review.

2021-07-24 08:14 UTC, akinwale approved these changes
Looks good! Thanks.

2021-07-24 08:14 UTC, merged